name: Build & publish

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/tex-builder:main
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: make

      - uses: actions/upload-artifact@v4
        with:
          name: |
            *.pdf

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: .
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: auto-release-${{ github.sha }}
          files: |
            *.pdf
